var prefix = [
  "met",//1
  "et",//2
  "prop",//3
  "but",//4
  "pent",//5
  "hekz",//6
  "hept",//7
  "okt",//8
  "non",//9
  "dek",//10
  "unodek",//11
  "didek",//12
  "tridek",//13
  "tetradek",//14
  "pentadek",//15
  "hekzadek",//16
  "heptadek",//17
  "oktadek",//18
  "nonadek",//19
  "ikos",//20
  "enaikos",//21
  "dikos",//22
  "trikos",//23
  "tetrakos",//24
  "pentakos",//25
  "hekzakos",//26
  "heptakos",//27
  "oktakos",//28
  "nonakos",//29
  "triakont",//30
  "enatriakont",//31
  "ditriakont",//32
  "tritriakont",//33
  "tetratriakont",//34
  "pentatriakont",//35
  "hekzatriakont",//36
  "heptatriakont",//37
  "oktatriakont",//38
  "nonatriakont",//39
  "tetrakont",//40
  "enatetrakont",//41
  "ditetrakont",//42
  "tritetrakont",//43
  "tetratetrakont",//44
  "pentatetrakont",//45
  "hekzatetrakont",//46
  "heptatetrakont",//47
  "oktatetrakont",//48
  "nonatetrakont",//49
  "pentakont",//50
  "enapentakont",//51
  "dipentakont",//52
  "tripentakont",//53
  "tetrapentakont",//54
  "pentapentakont",//55
  "hekzapentakont",//56
  "heptapentakont",//57
  "oktapentakont",//58
  "nonapentakont",//59
  "hekzakont",//60
  "enahekzakont",//61
  "dihekzakont",//62
  "trihekzakont",//63
  "tetrahekzakont",//64
  "pentahekzakont",//65
  "hekzahekzakont",//66
  "heptahekzakont",//67
  "oktahekzakont",//68
  "nonahekzakont",//69
  "heptakont",//70
  "enaheptakont",//71
  "diheptakont",//72
  "triheptakont",//73
  "tetraheptakont",//74
  "pentaheptakont",//75
  "hekzaheptakont",//76
  "heptaheptakont",//77
  "oktaheptakont",//78
  "nonaheptakont",//79
  "oktakont",//80
  "enaoktakont",//81
  "dioktakont",//82
  "trioktakont",//83
  "tetraoktakont",//84
  "pentaoktakont",//85
  "hekzaoktakont",//86
  "heptaoktakont",//87
  "oktaoktakont",//88
  "nonaoktakont",//89
  "nonakont",//90
  "enanonakont",//91
  "dinonakont",//92
  "trinonakont",//93
  "tetranonakont",//94
  "pentanonakont",//95
  "hekzanonakont",//96
  "heptanonakont",//97
  "oktanonakont",//98
  "nonanonakont",//99
  "hekt",//100
];