var number = [
  "",//1
  "di",//2
  "tri",//3
  "tetra",//4
  "penta",//5
  "hekza",//6
  "hepta",//7
  "okta",//8
  "nona",//9
  "deka",//10
  "unodeka",//11
  "dideka",//12
  "trideka",//13
  "tetradeka",//14
  "pentadeka",//15
  "hekzadeka",//16
  "heptadeka",//17
  "oktadeka",//18
  "nonadeka",//19
  "ikosa",//20
  "enaikosa",//21
  "dikosa",//22
  "trikosa",//23
  "tetrakosa",//24
  "pentakosa",//25
  "hekzakosa",//26
  "heptakosa",//27
  "oktakosa",//28
  "nonakosa",//29
  "triakonta",//30
  "enatriakonta",//31
  "ditriakonta",//32
  "tritriakonta",//33
  "tetratriakonta",//34
  "pentatriakonta",//35
  "hekzatriakonta",//36
  "heptatriakonta",//37
  "oktatriakonta",//38
  "nonatriakonta",//39
  "tetrakonta",//40
  "enatetrakonta",//41
  "ditetrakonta",//42
  "tritetrakonta",//43
  "tetratetrakonta",//44
  "pentatetrakonta",//45
  "hekzatetrakonta",//46
  "heptatetrakonta",//47
  "oktatetrakonta",//48
  "nonatetrakonta",//49
  "pentakonta",//50
  "enapentakonta",//51
  "dipentakonta",//52
  "tripentakonta",//53
  "tetrapentakonta",//54
  "pentapentakonta",//55
  "hekzapentakonta",//56
  "heptapentakonta",//57
  "oktapentakonta",//58
  "nonapentakonta",//59
  "hekzakonta",//60
  "enahekzakonta",//61
  "dihekzakonta",//62
  "trihekzakonta",//63
  "tetrahekzakonta",//64
  "pentahekzakonta",//65
  "hekzahekzakonta",//66
  "heptahekzakonta",//67
  "oktahekzakonta",//68
  "nonahekzakonta",//69
  "heptakonta",//70
  "enaheptakonta",//71
  "diheptakonta",//72
  "triheptakonta",//73
  "tetraheptakonta",//74
  "pentaheptakonta",//75
  "hekzaheptakonta",//76
  "heptaheptakonta",//77
  "oktaheptakonta",//78
  "nonaheptakonta",//79
  "oktakonta",//80
  "enaoktakonta",//81
  "dioktakonta",//82
  "trioktakonta",//83
  "tetraoktakonta",//84
  "pentaoktakonta",//85
  "hekzaoktakonta",//86
  "heptaoktakonta",//87
  "oktaoktakonta",//88
  "nonaoktakonta",//89
  "nonakonta",//90
  "enanonakonta",//91
  "dinonakonta",//92
  "trinonakonta",//93
  "tetranonakonta",//94
  "pentanonakonta",//95
  "hekzanonakonta",//96
  "heptanonakonta",//97
  "oktanonakonta",//98
  "nonanonakonta",//99
  "hekta",//100
];